config/routes.rb
Rails.application.routes.draw do
  root 'pages#top'

  get 'users/my'
  get 'users/index'
  resources :matches, only: :show

  devise_for :users, controllers: {
                       omniauth_callbacks: 'users/omniauth_callbacks',
                       sessions: 'users/sessions',
                       passwords: 'users/passwords',
                       confirmations: 'users/confirmations',
                       registrations: 'users/registrations',
                       unlocks: 'users/unlocks'
                   }
  devise_scope :user do
    get '/sign_in' => 'users/sessions#new'
    post 'sign_in' => 'users/sessions#create'
    delete '/sign_out' => 'users/sessions#new'
    get '/sign_up' => 'users/registrations#new'
    post '/sign_up' => 'users/registrations#create'
  end

  constraints Subdomain::Admin do
    namespace :admin, path: Subdomain::Admin.path do
      devise_for :admin_users, class_name: "Admin::AdminUser"
      root 'pages#index'
    end
  end

  constraints Subdomain::Api do
    namespace :api, path: Subdomain::Api.path do
    end
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/admin_user.rb
class Admin::AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/league.rb
class League < ActiveHash::Base
  include ActiveHash::Associations
  has_many :matches
end

app/models/match.rb
class Match < ActiveRecord::Base
  by_star_field :held_at
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :home_team, class_name: 'Team', shortcuts: %i(name api_name)
  belongs_to_active_hash :away_team, class_name: 'Team', shortcuts: %i(name api_name)
  belongs_to_active_hash :league

  enum flg: %i(plan end)


  validates :home_team_id, presence: true
  validates :away_team_id, presence: true
  validates :flg, presence: true
  validates :league_id, presence: true

  scope :home, ->(home_team_api_name) {
    home_team = Team.find_by_api_name(home_team_api_name)
    where('home_team_id = ?', home_team.id)
  }

  scope :away, ->(away_team_api_name) {
    away_team = Team.find_by_api_name(away_team_api_name)
    where('away_team_id = ?', away_team.id)
  }

  scope :own_league, -> (league_api_name) {
    league = League.find_by_api_name(league_api_name)
    where('league_id = ?', league.id)
  }
end

app/models/team.rb
class Team < ActiveHash::Base
  include ActiveHash::Associations
  has_many :matches
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i(twitter)

  class << self
    def from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = create_unique_email
        user.password = Devise.friendly_token[0, 20]
        user.name = auth.info.nickname   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image
      end
    end

    def create_unique_string
      SecureRandom.uuid
    end

    def create_unique_email
      User.create_unique_string + '@example.com'
    end
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::ApplicationController
  def index
  end
end

app/controllers/admin/passwords_controller.rb
class Admin::PasswordsController < Devise::PasswordsController
  layout 'admin/application'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  before_action :require_no_authentication, except: %i(new create destroy)
  layout 'admin/application'
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  # end

  # POST /resource/sign_in
#  def create
#  end

  # DELETE /resource/sign_out
#  def destroy
#    #super
#  end


  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end

  def after_sign_in_path_for(_resource)
    admin_root_path
  end

  def after_sign_out_path_for(_resource)
    admin_root_path
  end
end

app/controllers/admin/unlocks_controller.rb
class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #  def new_session_path(scope)
  #    new_user_session_path
  #  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    match = Match.find(params[:id])
    render locals: { match: match }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
    @matches = Match.past_week.presence || Match.before(Time.zone.now).limit(9)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def my
  end

  def index
  end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/index.html.slim
h1 Admin::Pages#index
p Find me in app/views/admin/pages/index.html.slim

app/views/layouts/_footer.html.slim
footer.footer
  .container
    p
      | kansen ©2015 All rights reserved.

app/views/layouts/_navbar.html.slim
/! Fixed navbar
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-controls='navbar' aria-expanded='false' data-target='#navbar' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Appname', root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle aria-expanded='false' data-toggle='dropdown' href='#' role='button'
              = current_user.name.presence || 'not found'
              span.caret
            ul.dropdown-menu role='menu'
              li
                = link_to current_user.name.presence || 'not found', users_my_path
              li
                = link_to 'logout', destroy_user_session_path, method: :delete
        - else
          li
            = link_to 'login', user_omniauth_authorize_path(provider: 'twitter')

app/views/layouts/admin/_footer.html.slim
footer.footer
  .container
    p
      | admin ©2015 All rights reserved.

app/views/layouts/admin/_navbar.html.slim
/! Fixed navbar
nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-controls='navbar' aria-expanded='false' data-target='#navbar' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Admin', admin_root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        - if admin_admin_user_signed_in?
          li.dropdown
            a.dropdown-toggle aria-expanded='false' data-toggle='dropdown' href='#' role='button'
              = current_admin_admin_user.email.presence || 'not found'
              span.caret
            ul.dropdown-menu role='menu'
              li
                = link_to current_admin_admin_user.email.presence || 'not found', admin_root_path
              li
                = link_to 'logout', destroy_admin_admin_user_session_path, method: :delete
        - else
          li
            = link_to 'login', new_admin_admin_user_session_path

app/views/layouts/admin/application.html.slim
doctype html
html
  head
    title
      | Admin
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css'
    = stylesheet_link_tag 'admin/application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js'
    = csrf_meta_tags
  body
    = render 'layouts/admin/navbar'
    .container
      = yield
    = render 'layouts/admin/footer'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Appname
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js'
    = csrf_meta_tags
  body
    = render 'layouts/navbar'
    .container
      = yield
    = render 'layouts/footer'

app/views/pages/top.html.slim
h1 最近の試合
p Find me in app/views/pages/top.html.slim
- @matches.each do |match|
  = link_to "#{match.home_team_name} vs #{match.away_team_name}", match_path(match.id)
  br